name: SmallRye Build

on:
  push:
    branches: 
      - master
      - mpconfig20
    paths-ignore:
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
      - 'NOTICE'
      - 'README*'
  pull_request:
    paths-ignore:
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
      - 'NOTICE'
      - 'README*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8, 11]
    name: build with jdk ${{matrix.java}}

    steps:
      - uses: actions/checkout@v2
        name: checkout

      - uses: actions/checkout@v2
        name: checkout mp 2.0
        with:
          repository: eclipse/microprofile-config
          path: microprofile-config

      - uses: actions/setup-java@v1.3.0
        name: set up jdk ${{matrix.java}}
        with:
          java-version: ${{matrix.java}}

      - name: build microprofile config
        run: |
          cd microprofile-config
          mvn install
          cd ..

      - name: build with maven
        run: mvn -B formatter:validate verify --file pom.xml
